### ISSUE TITLE
播放列表定位当前歌曲

### ISSUE THREAD

**Issue by cloudflypeng** [cloudflypeng/eno-music#12]

**Comment by jqtmviyu** [comment]
在左边导航栏再加个显示播放列表页可以吗? 同样属于定位的问题.

还有底部播放栏的快速收藏

**Comment by cloudflypeng** [comment]
<img width="305" alt="image" src="https://github.com/user-attachments/assets/96fd042e-1c1a-4ac3-8430-7c1d8cb99731">

增加播放状态logo

**Comment by cloudflypeng** [comment]
<img width="799" alt="image" src="https://github.com/user-attachments/assets/05cbd125-fffd-42c5-9939-9fb5ce610db5">

快捷添加
