### ISSUE TITLE
style: 媒体库收藏夹列表点击交互修改建议

### ISSUE THREAD

**Issue by Ares-Chang** [cloudflypeng/eno-music#20]
红框内鼠标经过无提示，以为不能点呢，黄色可交互区域太小了，不利于操作。

建议把  `cursor-pointer` 及展开逻辑提升至上一层，更加好懂一点当前是否可点击。

![image](https://github.com/user-attachments/assets/34d3cd84-82f5-4c1d-90c2-6781ad76f143)

**Comment by cloudflypeng** [comment]
感谢贡献
