### ISSUE TITLE
播放 API 被 B 站 ban 了

### ISSUE THREAD

**Issue by Jancat** [cloudflypeng/eno-music#22]
点击播放后，API 403

<img width="763" alt="image" src="https://github.com/user-attachments/assets/9f3f3c28-1423-42fc-ae2b-5f4f742a6cc3">

**Comment by cloudflypeng** [comment]
cdn问题, 这个不是播放接口,等有实力的大哥解决吧

**Comment by cloudflypeng** [comment]
兼容了xy开头的cdn切换成up开头的, 后续跟踪

**Comment by PoeraWork** [comment]
> 兼容了xy开头的cdn切换成up开头的, 后续跟踪

有Action版本吗，或者啥时候发版？
