### ISSUE TITLE
bug: 新增的小窗视频默认显示问题

### ISSUE THREAD

**Issue by Ares-Chang** [cloudflypeng/eno-music#30]
新用户进入后默认显示了

![image](https://github.com/user-attachments/assets/4e79d40e-8976-467a-b253-c3ee5160ec2d)

## 以下为个人对新功能的理解和建议

我觉得这个小窗可以做为可选项，而不是替换之前的全屏的纯享模式

我把它挪到点击歌曲图片那里是因为，操作习惯一般把那里当做歌词及写真集的纯享页面

个人觉得换成现在的小窗可能操作理解有误

**Comment by cloudflypeng** [comment]
可以先看一下youtube music的实现，我准备改成那样，还没做完
