### ISSUE TITLE
请问可以支持添加公开收藏夹的功能吗?

### ISSUE THREAD

**Issue by jqtmviyu** [cloudflypeng/eno-music#9]
以前在b站听到喜欢的歌都专门收藏到一个特定的文件夹.
~~我记得像 listen1 还是 yesplaymusic 就有类似的功能.~~

**Comment by cloudflypeng** [comment]
会的, 分p解析和收藏夹解析都在计划中

**Comment by cloudflypeng** [comment]
it's already
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/89311b45-cc71-455c-9761-9edce666cfce">

**Comment by cloudflypeng** [comment]
0.2.13 发布成功
